# Generated by Django 5.2.7 on 2026-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name="To'liq matn"),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name="To'liq matn"),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_uz',
            field=models.TextField(max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
