# Generated by Django 5.2.7 on 2025-12-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=300, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('icon', models.CharField(default='clipboard-check', help_text='Heroicons nomi: clipboard-check, beaker, shield-check va h.k.', max_length=50, verbose_name='Ikona')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order', 'title'],
            },
        ),
    ]
