# Generated by Django 5.2.7 on 2026-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Batafsil tavsif'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Batafsil tavsif'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
    ]
