# Generated by Django 5.2.7 on 2026-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
    ]
